<?php
/**
 * The Elementor element tree: ids, paths and operations.
 *
 * A page is a list of elements. Each has a stable "id" (seven hex digits,
 * generated by the editor), an "elType" (container, section, column,
 * widget), "settings" and its children in "elements"; a widget names its
 * kind in "widgetType". Operations address elements by id, because an id
 * survives every move while a position does not. Paths ("0.1") are given
 * alongside, for orientation only.
 *
 * Pure PHP on arrays, no WordPress and no Elementor, so every rule here is
 * tested without either (tests/elementor-data.php).
 *
 * @package wp-mcp-connector-plus
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Element types the classic editor builds with, and what each may hold.
 *
 * The rules Elementor's editor enforces when dragging: a page holds
 * containers or sections; a container holds containers and widgets; a
 * section holds columns; a column holds widgets and inner sections.
 *
 * @return array<string, string[]> elType => elTypes it may contain ('' is the page).
 */
function wpmcp_elementor_nesting() {
	return array(
		''          => array( 'container', 'section' ),
		'container' => array( 'container', 'widget' ),
		'section'   => array( 'column' ),
		'column'    => array( 'widget', 'section' ),
		'widget'    => array(),
	);
}

/**
 * Is this an element of the Atomic editor (Elementor 4's "e-" elements)?
 *
 * Those keep their settings as typed props ({"$$type": ...}) under rules
 * these tools do not know, so pages holding one are read but not written.
 *
 * @param array $element Element.
 * @return bool
 */
function wpmcp_elementor_is_atomic( array $element ) {
	foreach ( array( 'elType', 'widgetType' ) as $key ) {
		if ( isset( $element[ $key ] ) && is_string( $element[ $key ] ) && 0 === strpos( $element[ $key ], 'e-' ) ) {
			return true;
		}
	}
	return false;
}

/**
 * Decode stored `_elementor_data`.
 *
 * @param mixed $raw Meta value as stored (JSON text), or already decoded.
 * @return array|\WP_Error
 */
function wpmcp_elementor_decode( $raw ) {
	if ( is_array( $raw ) ) {
		return array_values( $raw );
	}
	if ( null === $raw || '' === $raw ) {
		return array();
	}

	$decoded = json_decode( (string) $raw, true );
	if ( ! is_array( $decoded ) ) {
		return new \WP_Error(
			'wpmcp_elementor_data_invalid',
			sprintf( 'The stored Elementor data of this page is not valid JSON (%s), so it cannot be read or changed here. Open the page in Elementor; its own save writes it again.', json_last_error_msg() )
		);
	}

	return array_values( $decoded );
}

/**
 * Every element id with its path.
 *
 * @param array $elements Element list.
 * @param int[] $prefix   Path of the list's parent.
 * @return array<string, int[]>
 */
function wpmcp_elementor_index( array $elements, array $prefix = array() ) {
	$index = array();
	foreach ( array_values( $elements ) as $i => $element ) {
		if ( ! is_array( $element ) ) {
			continue;
		}
		$path = array_merge( $prefix, array( $i ) );
		if ( isset( $element['id'] ) && is_scalar( $element['id'] ) ) {
			$index[ (string) $element['id'] ] = $path;
		}
		if ( ! empty( $element['elements'] ) && is_array( $element['elements'] ) ) {
			$index += wpmcp_elementor_index( $element['elements'], $path );
		}
	}
	return $index;
}

/**
 * The element at a path.
 *
 * @param array $elements Element list.
 * @param int[] $path     Path.
 * @return array|null
 */
function wpmcp_elementor_at( array $elements, array $path ) {
	$list = array_values( $elements );
	$node = null;
	foreach ( $path as $i ) {
		if ( ! isset( $list[ $i ] ) || ! is_array( $list[ $i ] ) ) {
			return null;
		}
		$node = $list[ $i ];
		$list = isset( $node['elements'] ) && is_array( $node['elements'] ) ? array_values( $node['elements'] ) : array();
	}
	return $node;
}

/**
 * The child list under a parent path ([] is the page).
 *
 * @param array $elements Element list.
 * @param int[] $parent   Parent path.
 * @return array
 */
function wpmcp_elementor_children( array $elements, array $parent ) {
	if ( empty( $parent ) ) {
		return array_values( $elements );
	}
	$node = wpmcp_elementor_at( $elements, $parent );
	return ( $node && isset( $node['elements'] ) && is_array( $node['elements'] ) ) ? array_values( $node['elements'] ) : array();
}

/**
 * Replace the child list under a parent path.
 *
 * @param array $elements Element list.
 * @param int[] $parent   Parent path ([] is the page).
 * @param array $children New children.
 * @return array
 */
function wpmcp_elementor_with_children( array $elements, array $parent, array $children ) {
	if ( empty( $parent ) ) {
		return array_values( $children );
	}
	$elements = array_values( $elements );
	$first    = array_shift( $parent );
	$node     = $elements[ $first ];
	$inner    = isset( $node['elements'] ) && is_array( $node['elements'] ) ? $node['elements'] : array();

	$node['elements']   = wpmcp_elementor_with_children( $inner, $parent, $children );
	$elements[ $first ] = $node;

	return $elements;
}

/**
 * Replace the element at a path.
 *
 * @param array $elements Element list.
 * @param int[] $path     Path.
 * @param array $element  New element.
 * @return array
 */
function wpmcp_elementor_replace_at( array $elements, array $path, array $element ) {
	$parent             = $path;
	$index              = array_pop( $parent );
	$children           = wpmcp_elementor_children( $elements, $parent );
	$children[ $index ] = $element;

	return wpmcp_elementor_with_children( $elements, $parent, $children );
}

/**
 * A path as text, the way the outline prints it.
 *
 * @param int[] $path Path.
 * @return string
 */
function wpmcp_elementor_path_string( array $path ) {
	return implode( '.', $path );
}

/**
 * A new element id, unique on the page.
 *
 * Seven lowercase hex digits, the shape Elementor's editor gives every
 * element (Math.random().toString(16).substr(2, 7)); the id ends up in
 * class names and in the per-page CSS file, so it has to look like one.
 *
 * @param array<string, bool> $taken Ids in use (by reference; the new one is added).
 * @return string
 */
function wpmcp_elementor_new_id( array &$taken ) {
	do {
		$id = substr( bin2hex( random_bytes( 4 ) ), 0, 7 );
	} while ( isset( $taken[ $id ] ) );

	$taken[ $id ] = true;

	return $id;
}

/**
 * Give an element and everything inside it new ids.
 *
 * @param array               $element Element.
 * @param array<string, bool> $taken   Ids in use (by reference).
 * @return array
 */
function wpmcp_elementor_reid( array $element, array &$taken ) {
	$element['id'] = wpmcp_elementor_new_id( $taken );
	if ( ! empty( $element['elements'] ) && is_array( $element['elements'] ) ) {
		foreach ( $element['elements'] as $i => $child ) {
			if ( is_array( $child ) ) {
				$element['elements'][ $i ] = wpmcp_elementor_reid( $child, $taken );
			}
		}
	}
	return $element;
}

/**
 * Set isInner the way the editor does, for an element and its subtree.
 *
 * A container inside another container is inner, a section inside a
 * column is inner, a column is as inner as its section. Widgets carry no
 * flag at all (Elementor removes it when it saves them).
 *
 * @param array      $element Element.
 * @param array|null $parent  Its parent, null on the page itself.
 * @return array
 */
function wpmcp_elementor_with_inner_flags( array $element, $parent ) {
	$type = (string) ( $element['elType'] ?? '' );

	if ( 'widget' === $type ) {
		unset( $element['isInner'] );
	} elseif ( 'column' === $type ) {
		$element['isInner'] = ! empty( $parent['isInner'] );
	} else {
		$element['isInner'] = null !== $parent;
	}

	if ( ! empty( $element['elements'] ) && is_array( $element['elements'] ) ) {
		foreach ( $element['elements'] as $i => $child ) {
			if ( is_array( $child ) ) {
				$element['elements'][ $i ] = wpmcp_elementor_with_inner_flags( $child, $element );
			}
		}
	}

	return $element;
}

/**
 * Number of elements in a subtree, the element itself included.
 *
 * @param array $element Element.
 * @return int
 */
function wpmcp_elementor_count( array $element ) {
	$count = 1;
	foreach ( (array) ( $element['elements'] ?? array() ) as $child ) {
		if ( is_array( $child ) ) {
			$count += wpmcp_elementor_count( $child );
		}
	}
	return $count;
}

/**
 * Elements on a page, all levels.
 *
 * @param array $elements Element list.
 * @return int
 */
function wpmcp_elementor_count_all( array $elements ) {
	$count = 0;
	foreach ( $elements as $element ) {
		if ( is_array( $element ) ) {
			$count += wpmcp_elementor_count( $element );
		}
	}
	return $count;
}

/**
 * A setting by dotted path ("html", "link.url", "tabs.0.tab_content").
 *
 * @param array  $settings Settings.
 * @param string $path     Dotted path.
 * @return mixed|null Null when it does not exist.
 */
function wpmcp_elementor_setting_get( array $settings, $path ) {
	$value = $settings;
	foreach ( explode( '.', (string) $path ) as $key ) {
		if ( ! is_array( $value ) || ! array_key_exists( $key, $value ) ) {
			return null;
		}
		$value = $value[ $key ];
	}
	return $value;
}

/**
 * Set a setting by dotted path. Only existing parents are walked.
 *
 * @param array  $settings Settings.
 * @param string $path     Dotted path.
 * @param mixed  $value    Value.
 * @return array
 */
function wpmcp_elementor_setting_set( array $settings, $path, $value ) {
	$keys = explode( '.', (string) $path );
	$key  = array_shift( $keys );

	if ( empty( $keys ) ) {
		$settings[ $key ] = $value;
		return $settings;
	}

	$inner            = isset( $settings[ $key ] ) && is_array( $settings[ $key ] ) ? $settings[ $key ] : array();
	$settings[ $key ] = wpmcp_elementor_setting_set( $inner, implode( '.', $keys ), $value );

	return $settings;
}

/**
 * Every string in every element's settings, keyed by where it sits.
 *
 * The unit the markup guard judges: "a1b2c3d:html", "f00ba12:link.url".
 *
 * @param array $elements Element list.
 * @return array<string, string>
 */
function wpmcp_elementor_strings( array $elements ) {
	$out = array();
	foreach ( $elements as $element ) {
		if ( ! is_array( $element ) ) {
			continue;
		}
		$id = (string) ( $element['id'] ?? '' );
		if ( isset( $element['settings'] ) && is_array( $element['settings'] ) ) {
			wpmcp_elementor_collect_strings( $element['settings'], $id . ':', $out );
		}
		if ( ! empty( $element['elements'] ) && is_array( $element['elements'] ) ) {
			$out += wpmcp_elementor_strings( $element['elements'] );
		}
	}
	return $out;
}

/**
 * Helper for wpmcp_elementor_strings().
 *
 * @param array  $value  Settings or part of them.
 * @param string $prefix Key so far.
 * @param array  $out    Result (by reference).
 */
function wpmcp_elementor_collect_strings( array $value, $prefix, array &$out ) {
	foreach ( $value as $key => $item ) {
		$name = ( ':' === substr( $prefix, -1 ) ) ? $prefix . $key : $prefix . '.' . $key;
		if ( is_string( $item ) ) {
			$out[ $name ] = $item;
		} elseif ( is_array( $item ) ) {
			wpmcp_elementor_collect_strings( $item, $name, $out );
		}
	}
}

/**
 * Elements of the Atomic editor on a page, by id.
 *
 * @param array $elements Element list.
 * @return string[]
 */
function wpmcp_elementor_atomic_ids( array $elements ) {
	$ids = array();
	foreach ( $elements as $element ) {
		if ( ! is_array( $element ) ) {
			continue;
		}
		if ( wpmcp_elementor_is_atomic( $element ) ) {
			$ids[] = (string) ( $element['id'] ?? '?' );
		}
		if ( ! empty( $element['elements'] ) && is_array( $element['elements'] ) ) {
			$ids = array_merge( $ids, wpmcp_elementor_atomic_ids( $element['elements'] ) );
		}
	}
	return $ids;
}

/**
 * The keys of an element the agent inserts.
 *
 * @return string[]
 */
function wpmcp_elementor_element_keys() {
	return array( 'elType', 'widgetType', 'settings', 'elements' );
}

/**
 * The keys each elementor-write operation takes.
 *
 * @return array<string, string[]>
 */
function wpmcp_elementor_op_keys() {
	return array(
		'patch_html'   => array( 'op', 'id', 'find', 'replace', 'all', 'setting' ),
		'set_html'     => array( 'op', 'id', 'html' ),
		'set_settings' => array( 'op', 'id', 'settings' ),
		'insert'       => array( 'op', 'element', 'elements', 'before', 'after', 'inside' ),
		'duplicate'    => array( 'op', 'id' ),
		'move'         => array( 'op', 'id', 'before', 'after', 'inside' ),
		'remove'       => array( 'op', 'id' ),
	);
}

/**
 * Turn an element as the agent sends it into one Elementor stores.
 *
 * Ids are always generated: an id the agent makes up could collide with
 * one elsewhere on the page, or with the element it copied the shape from.
 *
 * @param mixed               $spec  { elType, widgetType?, settings?, elements? }.
 * @param string              $where For messages, e.g. "Operation 2 (insert)".
 * @param array<string, bool> $taken Ids in use (by reference).
 * @return array|\WP_Error
 */
function wpmcp_elementor_build_element( $spec, $where, array &$taken ) {
	if ( ! is_array( $spec ) ) {
		return new \WP_Error( 'wpmcp_bad_element', sprintf( '%s: an element must be an object like {"elType":"widget","widgetType":"html","settings":{"html":"..."}}.', $where ) );
	}

	$type = $spec['elType'] ?? null;
	if ( ! is_string( $type ) || '' === $type ) {
		return new \WP_Error( 'wpmcp_bad_element', sprintf( '%s: "elType" is missing. Use container or widget (or section and column on pages built with sections).', $where ) );
	}
	if ( wpmcp_elementor_is_atomic( $spec ) ) {
		return new \WP_Error( 'wpmcp_elementor_atomic', sprintf( '%s: "%s" is an element of Elementor\'s Atomic editor, which these tools do not write.', $where, $spec['widgetType'] ?? $type ) );
	}
	// What the editor stores besides: "id" and "isInner" are taken as
	// elementor-read shows them and set anew. Anything else would be
	// dropped without a word, an element sent with "setting" was an empty
	// widget.
	// "path" is where elementor-read found it, decided here by the place.
	$unknown = wpmcp_unknown_keys( $spec, array_merge( wpmcp_elementor_element_keys(), array( 'id', 'isInner', 'path' ) ) );
	if ( ! empty( $unknown ) ) {
		return new \WP_Error(
			'wpmcp_unknown_key',
			wpmcp_unknown_keys_text( $where, $unknown, wpmcp_elementor_element_keys(), array( 'children' => 'elements', 'type' => 'elType', 'widget' => 'widgetType' ) )
				. ( in_array( 'html', $unknown, true ) ? ' The markup of an HTML widget goes in settings.html.' : '' )
				. ' "id" and "isInner" are accepted and set by the connector.'
		);
	}

	$nesting = wpmcp_elementor_nesting();
	if ( ! isset( $nesting[ $type ] ) || '' === $type ) {
		return new \WP_Error( 'wpmcp_bad_element', sprintf( '%s: elType "%s" is not one of container, section, column, widget.', $where, $type ) );
	}

	$element = array(
		'id'       => wpmcp_elementor_new_id( $taken ),
		'elType'   => $type,
		'settings' => array(),
		'elements' => array(),
	);

	if ( 'widget' === $type ) {
		$widget = $spec['widgetType'] ?? null;
		if ( ! is_string( $widget ) || ! preg_match( '/^[a-z0-9][a-z0-9_.-]*$/i', $widget ) ) {
			return new \WP_Error( 'wpmcp_bad_element', sprintf( '%s: a widget needs "widgetType", e.g. "html" or "heading".', $where ) );
		}
		$element['widgetType'] = $widget;
	}

	if ( isset( $spec['settings'] ) ) {
		if ( ! is_array( $spec['settings'] ) || ( ! empty( $spec['settings'] ) && array_keys( $spec['settings'] ) === range( 0, count( $spec['settings'] ) - 1 ) ) ) {
			return new \WP_Error( 'wpmcp_bad_element', sprintf( '%s: "settings" must be an object of setting => value.', $where ) );
		}
		$element['settings'] = $spec['settings'];
	}

	$children = $spec['elements'] ?? array();
	if ( ! is_array( $children ) ) {
		return new \WP_Error( 'wpmcp_bad_element', sprintf( '%s: "elements" must be a list.', $where ) );
	}
	foreach ( array_values( $children ) as $i => $child ) {
		$child_type = is_array( $child ) ? (string) ( $child['elType'] ?? '' ) : '';
		if ( ! in_array( $child_type, $nesting[ $type ], true ) ) {
			return new \WP_Error(
				'wpmcp_bad_element',
				sprintf( '%s: a %s cannot hold a %s (element %d inside it). A %s holds: %s.', $where, $type, '' === $child_type ? 'element without elType' : $child_type, $i, $type, empty( $nesting[ $type ] ) ? 'nothing' : implode( ', ', $nesting[ $type ] ) )
			);
		}
		$built = wpmcp_elementor_build_element( $child, $where, $taken );
		if ( is_wp_error( $built ) ) {
			return $built;
		}
		$element['elements'][] = $built;
	}

	return $element;
}

/**
 * Where an insert or move lands: parent path and index.
 *
 * Exactly one of before, after and inside; inside takes an element id or
 * "root" for the page itself, and appends.
 *
 * @param array  $elements Element list.
 * @param array  $op       Operation.
 * @param string $where    For messages.
 * @return array{0: int[], 1: int}|\WP_Error
 */
function wpmcp_elementor_resolve_place( array $elements, array $op, $where ) {
	$given = array_values( array_filter( array( 'before', 'after', 'inside' ), function ( $key ) use ( $op ) {
		return isset( $op[ $key ] ) && '' !== $op[ $key ];
	} ) );

	if ( 1 !== count( $given ) ) {
		return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: say where, with exactly one of "before", "after" (an element id) or "inside" (an element id, or "root" for the page).', $where ) );
	}

	$key    = $given[0];
	$target = (string) $op[ $key ];

	if ( 'inside' === $key && 'root' === $target ) {
		return array( array(), count( $elements ) );
	}

	$index = wpmcp_elementor_index( $elements );
	if ( ! isset( $index[ $target ] ) ) {
		return wpmcp_elementor_not_found( $where, $target );
	}
	$path = $index[ $target ];

	if ( 'inside' === $key ) {
		return array( $path, count( wpmcp_elementor_children( $elements, $path ) ) );
	}

	$parent = $path;
	$at     = array_pop( $parent );

	return array( $parent, 'before' === $key ? $at : $at + 1 );
}

/**
 * The error for an id that is not on the page.
 *
 * @param string $where For messages.
 * @param string $id    Id asked for.
 * @return \WP_Error
 */
function wpmcp_elementor_not_found( $where, $id ) {
	return new \WP_Error(
		'wpmcp_element_not_found',
		sprintf( '%s: there is no element with id "%s" on this page. Ids come from elementor-read; read the page again if it may have changed.', $where, $id )
	);
}

/**
 * Put elements into a parent's child list, if the parent may hold them.
 *
 * @param array  $elements Element list.
 * @param int[]  $parent   Parent path ([] is the page).
 * @param int    $at       Index.
 * @param array  $new      Elements to insert.
 * @param string $where    For messages.
 * @return array|\WP_Error
 */
function wpmcp_elementor_place( array $elements, array $parent, $at, array $new, $where ) {
	$parent_element = empty( $parent ) ? null : wpmcp_elementor_at( $elements, $parent );
	$parent_type    = null === $parent_element ? '' : (string) ( $parent_element['elType'] ?? '' );
	$nesting        = wpmcp_elementor_nesting();
	$allowed        = $nesting[ $parent_type ] ?? array();

	foreach ( $new as $element ) {
		$type = (string) ( $element['elType'] ?? '' );
		if ( ! in_array( $type, $allowed, true ) ) {
			return new \WP_Error(
				'wpmcp_bad_op',
				sprintf(
					'%s: a %s cannot go %s. %s holds: %s.',
					$where,
					$type,
					'' === $parent_type ? 'directly on the page' : 'inside a ' . $parent_type . ' (' . ( $parent_element['id'] ?? '?' ) . ')',
					'' === $parent_type ? 'The page' : 'A ' . $parent_type,
					empty( $allowed ) ? 'nothing' : implode( ', ', $allowed )
				)
			);
		}
	}

	$flagged = array();
	foreach ( $new as $element ) {
		$flagged[] = wpmcp_elementor_with_inner_flags( $element, $parent_element );
	}

	$children = wpmcp_elementor_children( $elements, $parent );
	array_splice( $children, max( 0, min( (int) $at, count( $children ) ) ), 0, $flagged );

	return wpmcp_elementor_with_children( $elements, $parent, $children );
}

/**
 * Apply operations to an element tree, in order.
 *
 * Shape only: what an element is allowed to hold, ids and anchors. Whether
 * a widget type exists, a setting is known and the markup may be stored is
 * decided on the result, against what is stored
 * (wpmcp_elementor_plan_write()).
 *
 * @param array $elements Element list as stored.
 * @param mixed $ops      Operations.
 * @return array{elements: array, summary: string[], confirm: array}|\WP_Error
 */
function wpmcp_elementor_apply_ops( array $elements, $ops ) {
	if ( ! is_array( $ops ) || empty( $ops ) || array_keys( $ops ) !== range( 0, count( $ops ) - 1 ) ) {
		return new \WP_Error( 'wpmcp_bad_request', 'Provide "ops": a non-empty list of operations.' );
	}

	$taken   = array_fill_keys( array_keys( wpmcp_elementor_index( $elements ) ), true );
	$summary = array();
	$confirm = array();

	foreach ( $ops as $n => $op ) {
		$name  = is_array( $op ) && is_string( $op['op'] ?? null ) ? $op['op'] : '';
		$where = sprintf( 'Operation %d (%s)', $n, '' === $name ? 'no "op"' : $name );

		if ( ! in_array( $name, array( 'patch_html', 'set_html', 'set_settings', 'insert', 'duplicate', 'move', 'remove' ), true ) ) {
			return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: "op" must be one of patch_html, set_html, set_settings, insert, duplicate, move, remove.', $where ) );
		}

		$accepted = wpmcp_elementor_op_keys()[ $name ];
		$unknown  = wpmcp_unknown_keys( $op, $accepted );
		if ( ! empty( $unknown ) ) {
			return new \WP_Error(
				'wpmcp_unknown_key',
				wpmcp_unknown_keys_text( $where, $unknown, $accepted, array( 'element_id' => 'id', 'elementId' => 'id', 'target' => 'inside', 'markup' => 'html' ) )
			);
		}

		if ( 'insert' === $name ) {
			$specs = isset( $op['elements'] ) ? $op['elements'] : ( isset( $op['element'] ) ? array( $op['element'] ) : null );
			if ( ! is_array( $specs ) || empty( $specs ) || array_keys( $specs ) !== range( 0, count( $specs ) - 1 ) ) {
				return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: give "element" (one element) or "elements" (a list).', $where ) );
			}
			$place = wpmcp_elementor_resolve_place( $elements, $op, $where );
			if ( is_wp_error( $place ) ) {
				return $place;
			}
			$built = array();
			foreach ( $specs as $spec ) {
				$element = wpmcp_elementor_build_element( $spec, $where, $taken );
				if ( is_wp_error( $element ) ) {
					return $element;
				}
				$built[] = $element;
			}
			$placed = wpmcp_elementor_place( $elements, $place[0], $place[1], $built, $where );
			if ( is_wp_error( $placed ) ) {
				return $placed;
			}
			$elements  = $placed;
			$ids       = array_column( $built, 'id' );
			$summary[] = sprintf( 'insert %s', implode( ', ', $ids ) );
			$confirm[] = array(
				'op'      => 'insert',
				'created' => $ids,
			);
			continue;
		}

		$id = isset( $op['id'] ) && is_scalar( $op['id'] ) ? (string) $op['id'] : '';
		if ( '' === $id ) {
			return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: "id" of the element is missing.', $where ) );
		}
		$index = wpmcp_elementor_index( $elements );
		if ( ! isset( $index[ $id ] ) ) {
			return wpmcp_elementor_not_found( $where, $id );
		}
		$path    = $index[ $id ];
		$element = wpmcp_elementor_at( $elements, $path );

		switch ( $name ) {
			case 'patch_html':
			case 'set_html':
				$is_html = 'widget' === ( $element['elType'] ?? '' ) && 'html' === ( $element['widgetType'] ?? '' );
				$setting = isset( $op['setting'] ) && is_string( $op['setting'] ) && '' !== $op['setting'] ? $op['setting'] : ( $is_html ? 'html' : '' );
				if ( 'set_html' === $name && ! $is_html ) {
					return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: element %s is a %s, not an HTML widget. Use set_settings for its settings.', $where, $id, $element['widgetType'] ?? $element['elType'] ?? 'element' ) );
				}
				if ( '' === $setting ) {
					return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: element %s is not an HTML widget, so say which text setting to patch with "setting" (e.g. "title" or "editor").', $where, $id ) );
				}
				$settings = isset( $element['settings'] ) && is_array( $element['settings'] ) ? $element['settings'] : array();
				$current  = wpmcp_elementor_setting_get( $settings, $setting );

				if ( 'set_html' === $name ) {
					if ( ! isset( $op['html'] ) || ! is_string( $op['html'] ) ) {
						return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: "html" must be the widget\'s whole new markup, as a string.', $where ) );
					}
					$element['settings'] = wpmcp_elementor_setting_set( $settings, 'html', $op['html'] );
					$elements            = wpmcp_elementor_replace_at( $elements, $path, $element );
					$summary[]           = sprintf( 'set_html %s', $id );
					$confirm[]           = array(
						'op'    => 'set_html',
						'id'    => $id,
						'bytes' => strlen( $op['html'] ),
					);
					break;
				}

				if ( ! is_string( $current ) ) {
					return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: setting "%s" of element %s is %s, not text.', $where, $setting, $id, null === $current ? 'not set' : gettype( $current ) ) );
				}
				$find = $op['find'] ?? null;
				if ( ! is_string( $find ) || '' === $find || ! array_key_exists( 'replace', $op ) || ! is_string( $op['replace'] ) ) {
					return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: give "find" (text that occurs in the setting) and "replace" (its replacement, may be empty).', $where ) );
				}
				$hits = substr_count( $current, $find );
				$all  = ! empty( $op['all'] );
				if ( 0 === $hits || ( $hits > 1 && ! $all ) ) {
					return new \WP_Error(
						'wpmcp_anchor_not_unique',
						0 === $hits
							? sprintf( '%s: the text to find does not occur in "%s" of element %s. Read the element again (elementor-read with element_id returns it verbatim, content-search gives the text around a hit).', $where, $setting, $id )
							: sprintf( '%s: the text to find occurs %d times in "%s" of element %s, so which one to change is not decided. Extend it until it is unique, or pass "all": true to change every one.', $where, $hits, $setting, $id )
					);
				}
				$position = strpos( $current, $find );
				$updated  = $all ? str_replace( $find, $op['replace'], $current ) : substr_replace( $current, $op['replace'], $position, strlen( $find ) );

				$element['settings'] = wpmcp_elementor_setting_set( $settings, $setting, $updated );
				$elements            = wpmcp_elementor_replace_at( $elements, $path, $element );
				$summary[]           = sprintf( 'patch_html %s', $id );
				$confirm[]           = array(
					'op'       => 'patch_html',
					'id'       => $id,
					'setting'  => $setting,
					'replaced' => $all ? $hits : 1,
					'now'      => wpmcp_elementor_excerpt( $updated, $position, strlen( $op['replace'] ) ),
				);
				break;

			case 'set_settings':
				$changes = $op['settings'] ?? null;
				if ( ! is_array( $changes ) || empty( $changes ) || array_keys( $changes ) === range( 0, count( $changes ) - 1 ) ) {
					return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: "settings" must be an object of setting => value (null removes a setting).', $where ) );
				}
				$settings = isset( $element['settings'] ) && is_array( $element['settings'] ) ? $element['settings'] : array();
				$set      = array();
				$removed  = array();
				foreach ( $changes as $key => $value ) {
					$key = (string) $key;
					if ( null === $value ) {
						unset( $settings[ $key ] );
						$removed[] = $key;
						continue;
					}
					$settings[ $key ] = $value;
					$set[]            = $key;
				}
				$element['settings'] = $settings;
				$elements            = wpmcp_elementor_replace_at( $elements, $path, $element );
				$summary[]           = sprintf( 'set_settings %s (%s)', $id, implode( ', ', array_merge( $set, $removed ) ) );
				$confirm[]           = array_filter(
					array(
						'op'      => 'set_settings',
						'id'      => $id,
						'set'     => $set,
						'removed' => $removed,
					)
				);
				break;

			case 'duplicate':
				$copy     = wpmcp_elementor_reid( $element, $taken );
				$parent   = $path;
				$at       = array_pop( $parent );
				$placed   = wpmcp_elementor_place( $elements, $parent, $at + 1, array( $copy ), $where );
				if ( is_wp_error( $placed ) ) {
					return $placed;
				}
				$elements  = $placed;
				$summary[] = sprintf( 'duplicate %s as %s', $id, $copy['id'] );
				$confirm[] = array(
					'op'       => 'duplicate',
					'id'       => $id,
					'created'  => array( $copy['id'] ),
					'elements' => wpmcp_elementor_count( $copy ),
				);
				break;

			case 'move':
				$parent   = $path;
				$at       = array_pop( $parent );
				$siblings = wpmcp_elementor_children( $elements, $parent );
				array_splice( $siblings, $at, 1 );
				$without = wpmcp_elementor_with_children( $elements, $parent, $siblings );

				// The target is looked up without the element, so it cannot
				// be the element itself or anything inside it.
				$place = wpmcp_elementor_resolve_place( $without, $op, $where );
				if ( is_wp_error( $place ) ) {
					if ( 'wpmcp_element_not_found' === $place->get_error_code() && isset( wpmcp_elementor_index( array( $element ) )[ (string) ( $op['before'] ?? $op['after'] ?? $op['inside'] ?? '' ) ] ) ) {
						return new \WP_Error( 'wpmcp_bad_op', sprintf( '%s: element %s cannot be moved next to or into itself or an element inside it.', $where, $id ) );
					}
					return $place;
				}
				$placed = wpmcp_elementor_place( $without, $place[0], $place[1], array( $element ), $where );
				if ( is_wp_error( $placed ) ) {
					return $placed;
				}
				$elements  = $placed;
				$summary[] = sprintf( 'move %s', $id );
				$confirm[] = array(
					'op' => 'move',
					'id' => $id,
				);
				break;

			case 'remove':
				$parent   = $path;
				$at       = array_pop( $parent );
				$siblings = wpmcp_elementor_children( $elements, $parent );
				array_splice( $siblings, $at, 1 );
				$elements  = wpmcp_elementor_with_children( $elements, $parent, $siblings );
				$summary[] = sprintf( 'remove %s', $id );
				$confirm[] = array_filter(
					array(
						'op'         => 'remove',
						'id'         => $id,
						'elType'     => $element['elType'] ?? null,
						'widgetType' => $element['widgetType'] ?? null,
						'elements'   => wpmcp_elementor_count( $element ),
					)
				);
				break;
		}
	}

	// Where everything ended up, now that every operation has run.
	$index = wpmcp_elementor_index( $elements );
	foreach ( $confirm as $i => $entry ) {
		if ( isset( $entry['id'] ) && isset( $index[ $entry['id'] ] ) ) {
			$confirm[ $i ]['path'] = wpmcp_elementor_path_string( $index[ $entry['id'] ] );
		}
		if ( isset( $entry['created'] ) ) {
			$confirm[ $i ]['paths'] = array_map(
				function ( $created ) use ( $index ) {
					return isset( $index[ $created ] ) ? wpmcp_elementor_path_string( $index[ $created ] ) : null;
				},
				$entry['created']
			);
		}
	}

	return array(
		'elements' => $elements,
		'summary'  => $summary,
		'confirm'  => $confirm,
	);
}

/**
 * The text around a replacement, cut at character boundaries.
 *
 * @param string $text   Whole setting.
 * @param int    $pos    Byte where the replacement starts.
 * @param int    $length Its length in bytes.
 * @return string
 */
function wpmcp_elementor_excerpt( $text, $pos, $length ) {
	$start = wpmcp_utf8_boundary( $text, max( 0, (int) $pos - 80 ) );
	$cut   = wpmcp_utf8_cut( $text, $start, ( (int) $pos - $start ) + (int) $length + 80 );

	return ( $start > 0 ? '...' : '' ) . trim( (string) preg_replace( '/\s+/', ' ', $cut ) );
}
